# Lab 01 : Convolutional layer - demo

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from random import randint

import time

# Table of contents 

1. Conv2D - output size, convolutional module, input,Feed it to the convolutional layer, Filter details
2. Conv3D - convolutional module, input,Feed it to the convolutional layer, Filter details
3. Conv1D - convolutional module, input,Feed it to the convolutional layer, Filter details
4. Pool layer - Input, Maxpooling - 2D, Average pooling - 2D
5. Building a Convolutional Neural Network
6. Building a Convolutional Neural Network - Training selective layers - Without changing require grad
7. Training selective layers - Changing the require grad to set False
8. Training a Covolutional Network - Training selective layers - Calculating gradients for only selective layers

# Conv2D

https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html

It is called 2 dimensional CNN because the kernel slides along 2 dimensions on the data

padding  – Zero-padding added to both sides of the input. Default: 0

## Output size

ouput size = [((input size + 2 * (padding) - covolution filter size)/stride) + 1] X [((input size + 2 * (padding) - covolution filter size)/stride) + 1]

In [6]:
input_size_x = 6
input_size_y = 6
padding_size = 1
filter_size = 3
stride_size = 1

ouput_size_height_x = (((input_size_x + 2 * (padding_size) - filter_size)/stride_size) + 1)
ouput_size_widtht_y = (((input_size_y + 2 * (padding_size) - filter_size)/stride_size) + 1)

print("Output size ---> height * width (X x Y) = ", ouput_size_height_x, " x ", ouput_size_widtht_y )

Output size ---> height * width (X x Y) =  6.0  x  6.0


# Convolutional module

in_channels – Number of channels in the input image

out_channels – Number of channels produced by the convolution // Number of filters

kernel_size – Size of the convolving kernel // filter size

stride – Stride of the convolution. Default: 1

padding – Zero-padding added to both sides of the input. Default: "0". Add "1" to produce the output with original
          image size.
          
* The parameters kernel_size, stride, padding can either be:
      a single int – in which case the same value is used for the height and width dimension
      a tuple of two ints – in which case, the first int is used for the height dimension, and the second int for the width dimension

In [7]:
mod2 = nn.Conv2d( in_channels = 2 ,out_channels= 5 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
print(mod2)

Conv2d(2, 5, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


# Input

### Input size = (batch size, Number of channels, height of input planes in pixels,width in pixels)



In [8]:
#### Input parameters

batch_size =1
no_of_channels = 2
x_size = 6
y_size = 6


inputs=torch.rand(batch_size,no_of_channels,x_size,y_size)

#print(inputs)

print(inputs.size())

torch.Size([1, 2, 6, 6])


# Feed it to the convolutional layer

### output size = (batch size, Number of channels, height of input planes in pixels,width in pixels)

In [9]:
outputs =mod2(inputs)

#print(outputs)

print(outputs.size())

torch.Size([1, 5, 6, 6])


# Filter details

shape of the filter = (out channels, in_channels/groups, kernel size [0], kernel size[1])

In [10]:
print(mod2.weight)

print(mod2.weight.size())

Parameter containing:
tensor([[[[ 0.0046,  0.2058,  0.0759],
          [-0.1728,  0.0153, -0.0083],
          [-0.1753, -0.1969, -0.2186]],

         [[-0.1168,  0.1260, -0.0864],
          [ 0.2334, -0.0907, -0.1392],
          [-0.0050,  0.1673,  0.2011]]],


        [[[ 0.0202, -0.1735,  0.0530],
          [-0.1257, -0.0477, -0.0345],
          [-0.1257,  0.0654, -0.0602]],

         [[-0.1841,  0.2178,  0.1129],
          [ 0.0427, -0.1315,  0.0625],
          [-0.0392, -0.2224, -0.1624]]],


        [[[-0.0291, -0.0650,  0.0658],
          [-0.1683, -0.1576, -0.0220],
          [-0.0376,  0.0925, -0.0486]],

         [[-0.0338,  0.1455, -0.1254],
          [-0.1232, -0.0795, -0.0627],
          [ 0.1812,  0.2340,  0.1318]]],


        [[[ 0.0695, -0.2305,  0.1488],
          [-0.0037, -0.0168, -0.1729],
          [-0.0220, -0.0659, -0.2160]],

         [[ 0.1992, -0.0969,  0.0294],
          [-0.2220, -0.0050,  0.0634],
          [ 0.0923, -0.1641, -0.1985]]],


        [[[ 0.1215

# Conv 3D

https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html

In Conv3D, the kernel slides in 3 dimensions as shown below

# Convolutional module

in_channels  – Number of channels in the input image

out_channels – Number of channels produced by the convolution

kernel_size – Size of the convolving kernel

stride  – Stride of the convolution. Default: 1

padding – Zero-padding added to both sides of the input. Default: 0. Add "1" to produce the output with original
          image size.
          
* The parameters kernel_size, stride, padding can either be:
      a single int – in which case the same value is used for the height and width dimension
      a tuple of two ints – in which case, the first int is used for the height dimension, and the second int for the width dimension

In [11]:
mod3 = nn.Conv3d( in_channels = 2 ,out_channels= 5 ,  kernel_size=3,  padding=0, stride = 1, bias = True )
print(mod3)

Conv3d(2, 5, kernel_size=(3, 3, 3), stride=(1, 1, 1))


# Input

### Input size = (batch size, Number of channels, Depth in pixels, height in pixels, width in pixels)


In [12]:
#### Input parameters

batch_size =1
no_of_channels = 2
x_size = 6
y_size = 6
z_size = 6

inputs=torch.rand(batch_size,no_of_channels,z_size, x_size,y_size)

#print(inputs)

print(inputs.size())

torch.Size([1, 2, 6, 6, 6])


# Feed it to the convolutional layer

### output size = (batch size, Number of channels, Depth in pixels, height of in pixels,width in pixels)

In [13]:
outputs = mod3(inputs)
print(outputs)
print(outputs.size())

tensor([[[[[-9.5384e-02, -7.6374e-02, -5.8460e-02, -5.2465e-02],
           [-2.1057e-01,  2.2044e-01, -1.8966e-01,  8.1242e-02],
           [ 5.6768e-03,  7.7819e-03,  1.0528e-01, -4.0486e-02],
           [-3.2426e-01,  4.1704e-01, -2.3334e-01,  1.3273e-01]],

          [[-4.3249e-02, -4.5646e-03, -1.7749e-01, -1.2097e-01],
           [-6.6949e-03, -1.5196e-01,  3.2973e-01, -2.0342e-01],
           [-1.7642e-01, -1.4975e-02, -1.8269e-01,  2.3286e-01],
           [-1.3369e-01, -6.7744e-02, -7.0190e-02, -1.9254e-01]],

          [[-2.3403e-01, -1.2734e-01,  1.8178e-01, -1.1963e-01],
           [ 2.7236e-01, -1.1842e-01,  3.8098e-02, -1.5360e-01],
           [-6.2583e-02,  1.7749e-01,  2.2805e-01, -1.3740e-01],
           [-2.2903e-01, -1.8970e-01, -2.5917e-01, -9.5373e-02]],

          [[-1.1529e-01, -7.5615e-02,  1.2110e-02,  4.6402e-02],
           [-1.5024e-01,  1.5261e-01, -6.4223e-02,  1.1729e-01],
           [ 9.3886e-02, -1.8349e-01,  3.2561e-02,  5.6293e-02],
           [-1.7476

# Filter details 

shape of the filter = (out channels, in_channels/groups, kernel size [0], kernel size[1], kernel size[2])

In [14]:
print(mod3.weight)

print(mod3.weight.size())

Parameter containing:
tensor([[[[[-0.1275,  0.1292,  0.0547],
           [ 0.0652,  0.0151,  0.1214],
           [-0.1137,  0.0088, -0.0495]],

          [[-0.0419, -0.0987,  0.0375],
           [-0.1298,  0.0189, -0.0965],
           [ 0.0608,  0.1344, -0.1354]],

          [[-0.0855,  0.0417,  0.0542],
           [-0.1357, -0.0965,  0.0590],
           [-0.0261,  0.0236, -0.0057]]],


         [[[ 0.0572,  0.1321,  0.0123],
           [-0.0037, -0.1159,  0.0468],
           [-0.0595,  0.0774, -0.1097]],

          [[ 0.0942, -0.0504,  0.1358],
           [-0.0935, -0.0027, -0.0909],
           [ 0.0869, -0.0548,  0.0010]],

          [[ 0.1328,  0.0837, -0.0151],
           [-0.0517, -0.1261,  0.1211],
           [ 0.0231,  0.0039, -0.0797]]]],



        [[[[-0.0036,  0.1107,  0.0135],
           [ 0.0498, -0.0051, -0.0741],
           [ 0.0077, -0.0521,  0.0702]],

          [[-0.1260, -0.0714,  0.1133],
           [-0.0400,  0.1328, -0.1222],
           [-0.1070,  0.0529,  0.1296]

# Conv 1D

https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html

In Conv1D, kernel slides along one dimension.

# Convolutional module

in_channels  – Number of channels in the input image

out_channels – Number of channels produced by the convolution

kernel_size – Size of the convolving kernel

stride  – Stride of the convolution. Default: 1

padding – Zero-padding added to both sides of the input. Default: 0. Add "1" to produce the output with original
          image size.


In [15]:
mod1 = nn.Conv1d( in_channels = 2 ,out_channels= 6 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
print(mod1)

Conv1d(2, 6, kernel_size=(3,), stride=(1,), padding=(1,))


# Input

### Input size = (batch size, Number of channels, Length of signal sequence)

In [16]:
#### Input parameters

batch_size =1
no_of_channels = 2
x_size = 6


inputs=torch.rand(batch_size,no_of_channels,x_size)

#print(inputs)

print(inputs.size())

torch.Size([1, 2, 6])


# Feed it to the convolutional layer

### output size = (batch size, Number of channels, Length of signal sequence)

In [17]:
outputs = mod1(inputs)
print(outputs)
print(outputs.size())

tensor([[[ 0.3027,  0.4715,  0.1583, -0.0444,  0.3831,  0.0643],
         [-0.1470,  0.0680, -0.0932, -0.1853,  0.1144,  0.0015],
         [ 0.3217,  0.4871,  0.6171,  0.4499,  0.4386,  0.4325],
         [-0.3422, -0.4852, -0.2199, -0.4243, -0.3130, -0.0771],
         [-0.0142, -0.4091, -0.0311, -0.1933, -0.3236,  0.0084],
         [ 0.0366,  0.1517,  0.2805,  0.0790,  0.2337,  0.2799]]],
       grad_fn=<SqueezeBackward1>)
torch.Size([1, 6, 6])


# Filter details

shape of the filter = (out channels, in_channels/groups, kernel size)

In [18]:
print(mod1.weight)

print(mod1.weight.size())

Parameter containing:
tensor([[[-0.1982,  0.0289,  0.3938],
         [-0.1987, -0.0305,  0.1147]],

        [[-0.2510, -0.3336,  0.0448],
         [ 0.1805,  0.3695,  0.2524]],

        [[ 0.3172,  0.3645,  0.1693],
         [-0.0716,  0.1157,  0.0139]],

        [[-0.0985, -0.3352, -0.3319],
         [ 0.0045,  0.3523, -0.1333]],

        [[ 0.0248,  0.0922, -0.3409],
         [-0.2519, -0.1192, -0.3820]],

        [[ 0.0700, -0.0693, -0.0908],
         [ 0.0180,  0.3867,  0.0828]]], requires_grad=True)
torch.Size([6, 2, 3])


# Pool layer

https://pytorch.org/docs/stable/nn.html#pooling-layers

# Input

### Input size = (batch size, Number of channels, height of  in pixels,width in pixels)

In [19]:
#### Input parameters

batch_size =1
no_of_channels = 2
x_size = 6
y_size = 6


inputs=torch.rand(batch_size,no_of_channels,x_size,y_size)

#print(inputs)

print(inputs.size())

torch.Size([1, 2, 6, 6])


# Maxpooling - 2D

https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html

torch.nn.MaxPool2d(kernel_size,stride)

The parameters kernel_size, stride, padding, dilation can either be:

     * a single int – in which case the same value is used for the height and width dimension

     * a tuple of two ints – in which case, the first int is used for the height dimension, and the second int for the width dimension

In [20]:
poolmax = nn. MaxPool2d(kernel_size =3)

In [21]:
output = poolmax(inputs)
print(output)
print(output.size())

tensor([[[[0.9928, 0.9674],
          [0.9933, 0.9568]],

         [[0.8408, 0.8829],
          [0.8595, 0.8817]]]])
torch.Size([1, 2, 2, 2])


In [22]:
poolmax = nn. MaxPool2d(kernel_size =(2,3))

In [23]:
output = poolmax(inputs)
print(output)
print(output.size())

tensor([[[[0.8699, 0.9674],
          [0.9933, 0.7391],
          [0.9112, 0.9568]],

         [[0.8002, 0.8829],
          [0.8595, 0.7710],
          [0.8044, 0.8817]]]])
torch.Size([1, 2, 3, 2])


# Average pooling - 2D

https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html#torch.nn.AvgPool2d

The parameters kernel_size, stride, padding, dilation can either be:

     * a single int – in which case the same value is used for the height and width dimension

     * a tuple of two ints – in which case, the first int is used for the height dimension, and the second int for the width dimension

In [24]:
poolave = nn. AvgPool2d(kernel_size =3)

In [25]:
output = poolave(inputs)
print(output)
print(output.size())

tensor([[[[0.5678, 0.6247],
          [0.4574, 0.5733]],

         [[0.4663, 0.5019],
          [0.3710, 0.4459]]]])
torch.Size([1, 2, 2, 2])


In [26]:
poolave = nn. MaxPool2d(kernel_size =(2,3))

In [27]:
output = poolave(inputs)
print(output)
print(output.size())

tensor([[[[0.8699, 0.9674],
          [0.9933, 0.7391],
          [0.9112, 0.9568]],

         [[0.8002, 0.8829],
          [0.8595, 0.7710],
          [0.8044, 0.8817]]]])
torch.Size([1, 2, 3, 2])


# Building a Convolutional Neural Network

### Strategy

    1. At each convolution layer - double the feature number (in_channels to out_channels (i.e 2 times of in_channels)) at each convolution layer
    2. At each maxpooling layer - reduce the size of the image by 2 // Also useful in creating global invariance
    
Note: Trading image resolution with features number. Controlling the computational complexity. (Image size/2 and #features X 2)

The convolutional and maxpooling layers are used for feature extraction. Linear layers are used for classification.

Reshape i.e. Flatten the extracted features as (batch size, number of features) when passing through the linear layer 

In [28]:
class LeNet5_convnet(nn.Module):

    def __init__(self):

        super(LeNet5_convnet, self).__init__()
        self.convlayer1 = nn.Conv2d( in_channels = 1 ,out_channels= 50 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
        self.poolmax1 = nn. MaxPool2d(kernel_size =(2,2))
        self.convlayer2 = nn.Conv2d( in_channels = 50 ,out_channels= 100 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
        self.poolmax2 = nn. MaxPool2d(kernel_size =(2,2))
        self.linearlay1 = nn.Linear(in_features= 4900, out_features= 100, bias= True)
        self.linearlay2 = nn.Linear(in_features= 100, out_features= 10, bias= True)
        
        
    def forward(self, x):
        x = self.convlayer1(x)
        x = torch.relu(x)
        x = self.poolmax1(x)
        x = self.convlayer2(x)
        x = torch.relu(x)
        x = self.poolmax2(x)
        x = self.linearlay1(x.view(-1,4900))
        x =torch.relu(x)
        scores = self.linearlay2(x)
        
        return scores
        
convnet = LeNet5_convnet()
print(convnet)
        

LeNet5_convnet(
  (convlayer1): Conv2d(1, 50, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (poolmax1): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (convlayer2): Conv2d(50, 100, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (poolmax2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (linearlay1): Linear(in_features=4900, out_features=100, bias=True)
  (linearlay2): Linear(in_features=100, out_features=10, bias=True)
)


##  Choose the criterion, learning rate and batch size

In [29]:
criterion = nn.CrossEntropyLoss()
my_lr = 0.25
batch_size = 128

# Standardization

##to be updated

# Building a Convolutional Neural Network

## Training selective layers

## Without changing require grad


In [36]:
class LeNet5_convnet(nn.Module):

    def __init__(self):

        super(LeNet5_convnet, self).__init__()
        self.convlayer1 = nn.Conv2d( in_channels = 1 ,out_channels= 50 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
        self.poolmax1 = nn. MaxPool2d(kernel_size =(2,2))
        self.convlayer2 = nn.Conv2d( in_channels = 50 ,out_channels= 100 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
        self.poolmax2 = nn. MaxPool2d(kernel_size =(2,2))
        self.linearlay1 = nn.Linear(in_features= 4900, out_features= 100, bias= True)
        self.linearlay2 = nn.Linear(in_features= 100, out_features= 10, bias= True)
        
        
    def forward(self, x):
        x = self.convlayer1(x)
        x = torch.relu(x)
        x = self.poolmax1(x)
        x = self.convlayer2(x)
        x = torch.relu(x)
        x = self.poolmax2(x)
        x = self.linearlay1(x.view(-1,4900))
        x =torch.relu(x)
        scores = self.linearlay2(x)
        
        return scores
        
convnet = LeNet5_convnet()
print(convnet)

params_to_update = []

params_to_update.append(convnet.linearlay1.weight)
params_to_update.append(convnet.linearlay1.bias)
params_to_update.append(convnet.linearlay2.weight)
params_to_update.append(convnet.linearlay2.bias)
optimizer = torch.optim.SGD(params_to_update, lr = 0.01)


LeNet5_convnet(
  (convlayer1): Conv2d(1, 50, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (poolmax1): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (convlayer2): Conv2d(50, 100, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (poolmax2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (linearlay1): Linear(in_features=4900, out_features=100, bias=True)
  (linearlay2): Linear(in_features=100, out_features=10, bias=True)
)


# Training selective layers

## Changing the require grad to set False 

## Print the parameters of the neural network

In [193]:
for para in convnet.parameters():
    print(para)

Parameter containing:
tensor([[[[ 0.0071,  0.1068, -0.0454],
          [ 0.2926, -0.1510, -0.1374],
          [ 0.0025,  0.1758,  0.1319]]],


        [[[ 0.2712,  0.0553,  0.1335],
          [-0.1986,  0.3066,  0.3732],
          [-0.4060, -0.2521,  0.0982]]],


        [[[-0.2245, -0.3117, -0.2491],
          [ 0.2702, -0.0154, -0.0142],
          [-0.0144,  0.3369,  0.2535]]],


        [[[ 0.3096, -0.3216, -0.4718],
          [ 0.4489,  0.1130, -0.4053],
          [ 0.1480,  0.3235, -0.0321]]],


        [[[-0.1759, -0.2039,  0.1743],
          [-0.3593, -0.0804,  0.3286],
          [ 0.1851,  0.0781,  0.1895]]],


        [[[-0.0973, -0.2698,  0.3898],
          [-0.0594, -0.0993,  0.1710],
          [-0.2424, -0.2983,  0.1527]]],


        [[[-0.3749, -0.3594,  0.2022],
          [-0.4563,  0.2178,  0.2773],
          [-0.1261,  0.3639,  0.2167]]],


        [[[-0.2118, -0.0277, -0.2490],
          [-0.1617,  0.0597,  0.2289],
          [ 0.1238, -0.2537,  0.0563]]],


        [[

# Print only the name of the parameters of the Neural Network

In [192]:
for name, param in convnet.named_parameters():
    if param.requires_grad:print(name)

convlayer1.weight
convlayer1.bias
convlayer2.weight
convlayer2.bias
linearlay1.weight
linearlay1.bias
linearlay2.weight
linearlay2.bias


# Setting selected layers to false

In [182]:
for name, param in convnet.named_parameters():
    if param.requires_grad and 'convlayer1' in name:
        param.requires_grad = False
    if param.requires_grad and 'convlayer2' in name:
        param.requires_grad = False

## Verifying  the status of the parameters

In [184]:
for name, param in convnet.named_parameters():print(name, param)

convlayer1.weight Parameter containing:
tensor([[[[ 0.0071,  0.1068, -0.0454],
          [ 0.2926, -0.1510, -0.1374],
          [ 0.0025,  0.1758,  0.1319]]],


        [[[ 0.2712,  0.0553,  0.1335],
          [-0.1986,  0.3066,  0.3732],
          [-0.4060, -0.2521,  0.0982]]],


        [[[-0.2245, -0.3117, -0.2491],
          [ 0.2702, -0.0154, -0.0142],
          [-0.0144,  0.3369,  0.2535]]],


        [[[ 0.3096, -0.3216, -0.4718],
          [ 0.4489,  0.1130, -0.4053],
          [ 0.1480,  0.3235, -0.0321]]],


        [[[-0.1759, -0.2039,  0.1743],
          [-0.3593, -0.0804,  0.3286],
          [ 0.1851,  0.0781,  0.1895]]],


        [[[-0.0973, -0.2698,  0.3898],
          [-0.0594, -0.0993,  0.1710],
          [-0.2424, -0.2983,  0.1527]]],


        [[[-0.3749, -0.3594,  0.2022],
          [-0.4563,  0.2178,  0.2773],
          [-0.1261,  0.3639,  0.2167]]],


        [[[-0.2118, -0.0277, -0.2490],
          [-0.1617,  0.0597,  0.2289],
          [ 0.1238, -0.2537,  0.056

# Updating the optimiser to prevent the update weight

In [185]:
optimizer = optim.SGD(filter(lambda p: p.requires_grad, convnet.parameters()), lr=0.1)

## Verifying what's inside the optimiser

In [189]:
for p in filter(lambda p: p.requires_grad, convnet.parameters()):print(p)

Parameter containing:
tensor([[-0.0038,  0.0075, -0.0083,  ...,  0.0144, -0.0047, -0.0126],
        [ 0.0125, -0.0120, -0.0094,  ...,  0.0022,  0.0137, -0.0055],
        [ 0.0050,  0.0029,  0.0055,  ..., -0.0040,  0.0006, -0.0049],
        ...,
        [-0.0062,  0.0090,  0.0046,  ..., -0.0052, -0.0128,  0.0094],
        [ 0.0016, -0.0024,  0.0102,  ...,  0.0032,  0.0075, -0.0129],
        [ 0.0095, -0.0113,  0.0116,  ...,  0.0061, -0.0023, -0.0128]],
       requires_grad=True)
Parameter containing:
tensor([ 1.2555e-02,  2.7687e-02, -9.7321e-03,  5.8737e-03, -6.9799e-03,
         5.7178e-03, -1.3416e-02,  2.1739e-02,  5.1573e-02, -6.7927e-04,
         2.1248e-03,  9.8908e-03,  6.1670e-03,  1.3580e-02, -9.7686e-03,
        -1.5405e-02, -2.1356e-02, -1.5084e-02,  3.1093e-02, -1.3159e-02,
        -2.3479e-02,  2.3554e-02,  2.1097e-02, -1.8121e-02, -2.3029e-03,
        -2.1081e-03, -2.7799e-02, -1.3317e-02, -1.9470e-02, -1.4994e-02,
         3.2860e-02, -9.7700e-03, -7.4062e-03, -2.0641e-0

# Changing back everything to True

In [191]:
for para in convnet.parameters():
    para.requires_grad = True
    print(para)

Parameter containing:
tensor([[[[ 0.0071,  0.1068, -0.0454],
          [ 0.2926, -0.1510, -0.1374],
          [ 0.0025,  0.1758,  0.1319]]],


        [[[ 0.2712,  0.0553,  0.1335],
          [-0.1986,  0.3066,  0.3732],
          [-0.4060, -0.2521,  0.0982]]],


        [[[-0.2245, -0.3117, -0.2491],
          [ 0.2702, -0.0154, -0.0142],
          [-0.0144,  0.3369,  0.2535]]],


        [[[ 0.3096, -0.3216, -0.4718],
          [ 0.4489,  0.1130, -0.4053],
          [ 0.1480,  0.3235, -0.0321]]],


        [[[-0.1759, -0.2039,  0.1743],
          [-0.3593, -0.0804,  0.3286],
          [ 0.1851,  0.0781,  0.1895]]],


        [[[-0.0973, -0.2698,  0.3898],
          [-0.0594, -0.0993,  0.1710],
          [-0.2424, -0.2983,  0.1527]]],


        [[[-0.3749, -0.3594,  0.2022],
          [-0.4563,  0.2178,  0.2773],
          [-0.1261,  0.3639,  0.2167]]],


        [[[-0.2118, -0.0277, -0.2490],
          [-0.1617,  0.0597,  0.2289],
          [ 0.1238, -0.2537,  0.0563]]],


        [[

# Training  a Covolutional Network

## Training selective layers

## Calculating gradients for only selective layers

In [35]:
%reset -f

import torch
import torch.nn as nn


class LeNet5_convnet(nn.Module):

    def __init__(self):

        super(LeNet5_convnet, self).__init__()
        self.convlayer1 = nn.Conv2d( in_channels = 1 ,out_channels= 50 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
        self.poolmax1 = nn. MaxPool2d(kernel_size =(2,2))
        self.convlayer2 = nn.Conv2d( in_channels = 50 ,out_channels= 100 ,  kernel_size=3,  padding=1, stride = 1, bias = True )
        self.poolmax2 = nn. MaxPool2d(kernel_size =(2,2))
        self.linearlay1 = nn.Linear(in_features= 4900, out_features= 100, bias= True)
        self.linearlay2 = nn.Linear(in_features= 100, out_features= 10, bias= True)
        
        
    def forward(self, x):
        x = self.convlayer1(x)
        x = torch.relu(x)
        x = self.poolmax1(x)
        x = self.convlayer2(x)
        x = torch.relu(x)
        x = self.poolmax2(x)
        x = self.linearlay1(x.view(-1,4900))
        x =torch.relu(x)
        scores = self.linearlay2(x)
        
        return scores
        
convnet = LeNet5_convnet()
print(convnet)

for name, param in convnet.named_parameters():
    if param.requires_grad and 'convlayer1' in name:
        param.requires_grad = False
    if param.requires_grad and 'convlayer2' in name:
        param.requires_grad = False

params_to_update = []

params_to_update.append(convnet.linearlay1.weight)
params_to_update.append(convnet.linearlay1.bias)
params_to_update.append(convnet.linearlay2.weight)
params_to_update.append(convnet.linearlay2.bias)
print(params_to_update)
optimizer = torch.optim.SGD(params_to_update, lr = 0.01)


LeNet5_convnet(
  (convlayer1): Conv2d(1, 50, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (poolmax1): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (convlayer2): Conv2d(50, 100, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (poolmax2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (linearlay1): Linear(in_features=4900, out_features=100, bias=True)
  (linearlay2): Linear(in_features=100, out_features=10, bias=True)
)
[Parameter containing:
tensor([[ 0.0101,  0.0073, -0.0081,  ...,  0.0053,  0.0112, -0.0072],
        [ 0.0027, -0.0139,  0.0065,  ..., -0.0141, -0.0019, -0.0055],
        [-0.0100, -0.0099, -0.0096,  ..., -0.0081,  0.0134, -0.0111],
        ...,
        [ 0.0135,  0.0034, -0.0068,  ..., -0.0093, -0.0096,  0.0033],
        [ 0.0105, -0.0129,  0.0025,  ...,  0.0125,  0.0096, -0.0001],
        [-0.0028, -0.0037,  0.0130,  ...,  0.0048, -0.0104,  0.0125]],
       requires_grad=True